version: "3.9"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASS: ""
      DB_NAME: nodejsbasic
